#!/usr/bin/make
#
#
# http://doc.devpi.net/latest/index.html

include ../utils/pre-var.mk
include ../paths.mk

ifneq ($(wildcard certs.pem.in),)
_SYSTEM_CERTS_FILE := $(SYSTEM_CERTS_FILE)
endif

include ../utils/post-var.mk

