#!/usr/bin/make
#
# Makefile for tmux assistance.
#
# Created on: 04.11.16

include ../utils/utils.mk

### Variables ###

### Rules ###
.PHONY: config install
config: tmux.check

install: tmux.install
